import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Swamal",
    image: "https://m.media-amazon.com/images/I/81EUM5ANI7L._SX679_.jpg",
    brand: "Dhootpapeshwar",
    price: "500",
    weight: "1kg",
    ratings: 3.5,
    categoryName: "Avaleha",
    fastDelivery: true,
    inStock: true,
  },
  {
    _id: uuid(),
    title: "Aarogyavardhini",
    image: "https://m.media-amazon.com/images/I/41K8xNjuHVL.jpg",
    brand: "Dhootpapeshwar",
    price: "350",
    weight: "500gm",
    ratings: 4,
    categoryName: "Rasayana",
    fastDelivery: true,
    inStock: true,
  },
  {
    _id: uuid(),
    title: "Triphala Churna",
    image:
      "https://images-eu.ssl-images-amazon.com/images/I/41sGBq-4aWL._SX300_SY300_QL70_FMwebp_.jpg",
    brand: "Dhootpapeshwar",
    price: "150",
    weight: "50gm",
    ratings: 4.5,
    categoryName: "Churna",
    fastDelivery: false,
    inStock: false,
  },
  {
    _id: uuid(),
    title: "SuvarnaKalpa",
    image:
      "https://images-eu.ssl-images-amazon.com/images/I/51m2VwSZDoL._SX300_SY300_QL70_FMwebp_.jpg",
    brand: "Dhootpapeshwar",
    price: "90",
    weight: "30 items",
    ratings: 5,
    categoryName: "Vati",
    fastDelivery: true,
    inStock: true,
  },
  {
    _id: uuid(),
    title: "Anu Taila",
    image:
      "https://images-eu.ssl-images-amazon.com/images/I/41xxfI0YDpS._SX300_SY300_QL70_FMwebp_.jpg",
    brand: "Dhootpapeshwar",
    price: "110",
    weight: "30ml",
    ratings: 4,
    categoryName: "Taila",
    fastDelivery: false,
    inStock: false,
  },
  {
    _id: uuid(),
    title: "Atmaprash",
    image: "https://www.santulan.in/wp-content/uploads/2020/04/Atmaprash-1.png",
    brand: "Santulan",
    price: "500",
    weight: "700gm",
    ratings: 3,
    categoryName: "Avaleha",
    fastDelivery: false,
    inStock: true,
  },
  {
    _id: uuid(),
    title: "CHyavanprash",
    image:
      "https://www.santulan.in/wp-content/uploads/2020/04/chyavanprash2-1.png",
    brand: "Santulan",
    price: "450",
    weight: "500gm",
    ratings: 5,
    categoryName: "Rasayana",
    fastDelivery: true,
    inStock: true,
  },
  {
    _id: uuid(),
    title: "Bramhi",
    image: "https://www.santulan.in/wp-content/uploads/2020/04/San-Brahmi.png",
    brand: "Santulan",
    price: "100",
    weight: "50gm",
    ratings: 4.5,
    categoryName: "Churna",
    fastDelivery: true,
    inStock: true,
  },
  {
    _id: uuid(),
    title: "Lohit Plus",
    image:
      "https://www.santulan.in/wp-content/uploads/2020/04/Lohit-Plus-1.png",
    brand: "Santulan",
    price: "80",
    weight: "10 items",
    ratings: 4,
    categoryName: "Vati",
    fastDelivery: false,
    inStock: false,
  },
  {
    _id: uuid(),
    title: "Abhyanga(s)",
    image: "https://www.santulan.in/wp-content/uploads/2020/04/10.png",
    brand: "Santulan",
    price: "300",
    weight: "50ml",
    ratings: 3.5,
    categoryName: "Taila",
    fastDelivery: true,
    inStock: true,
  },
  {
    _id: uuid(),
    title: "Haritaki",
    image:
      "https://m.media-amazon.com/images/I/31I3Q-pn0yL._AC_UL480_FMwebp_QL65_.jpg",
    brand: "Dabar",
    price: "250",
    weight: "500gm",
    ratings: 5,
    categoryName: "Avaleha",
    fastDelivery: false,
    inStock: false,
  },
  {
    _id: uuid(),
    title: "Shwasamrit",
    image:
      "https://m.media-amazon.com/images/I/61EFru72B8S._AC_UL480_QL65_.jpg",
    brand: "Dabar",
    price: "300",
    weight: "250gm",
    ratings: 4,
    categoryName: "Rasayana",
    fastDelivery: false,
    inStock: true,
  },
  {
    _id: uuid(),
    title: "Aswagandha",
    image:
      "https://m.media-amazon.com/images/I/71-zTf6EtML._AC_UL480_QL65_.jpg",
    brand: "Dabar",
    price: "125",
    weight: "75gm",
    ratings: 4.5,
    categoryName: "Churna",
    fastDelivery: true,
    inStock: true,
  },
  {
    _id: uuid(),
    title: "Tulasi tab",
    image:
      "https://m.media-amazon.com/images/I/81z1211hOjL._AC_UL480_FMwebp_QL65_.jpg",
    brand: "Dabar",
    price: "60",
    weight: "20 items",
    ratings: 3.5,
    categoryName: "Vati",
    fastDelivery: false,
    inStock: true,
  },
  {
    _id: uuid(),
    title: "Badam Oil",
    image:
      "https://m.media-amazon.com/images/I/711R+Q-zLmS._AC_UL480_FMwebp_QL65_.jpg",
    brand: "Dabar",
    price: "100",
    weight: "100ml",
    ratings: 3,
    categoryName: "Taila",
    fastDelivery: true,
    inStock: false,
  },
  {
    _id: uuid(),
    title: "Chyavanprash",
    image: "https://images.meesho.com/images/products/82823464/lpt3b_512.jpg",
    brand: "Patanjali",
    price: "300",
    weight: "200gm",
    ratings: 5,
    categoryName: "Avaleha",
    fastDelivery: false,
    inStock: true,
  },
  {
    _id: uuid(),
    title: "Amrut Rasayana",
    image:
      "https://onemg.gumlet.io/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1608224541/cropped/drhjnqw91hsf4jmhlsfw.jpg",
    brand: "Patanjali",
    price: "500",
    weight: "500gm",
    ratings: 4,
    categoryName: "Rasayana",
    fastDelivery: true,
    inStock: false,
  },
  {
    _id: uuid(),
    title: "Pushyanga Churna",
    image:
      "https://www.patanjaliayurved.net/assets/product_images/400x300/1504942479400%20x%20300%20Pushyanug%20Churna.png",
    brand: "Patanjali",
    price: "40",
    weight: "20gm",
    ratings: 4.5,
    categoryName: "Churna",
    fastDelivery: true,
    inStock: true,
  },
  {
    _id: uuid(),
    title: "Medha Vati",
    image:
      "https://m.media-amazon.com/images/I/412hqfpBz3L._AC_UL480_FMwebp_QL65_.jpg",
    brand: "Patanjali",
    price: "80",
    weight: "20 items",
    ratings: 3.5,
    categoryName: "Vati",
    fastDelivery: false,
    inStock: true,
  },
  {
    _id: uuid(),
    title: "Coconut Oil",
    image:
      "https://m.media-amazon.com/images/I/41AKJ9IitaL._AC_UL480_FMwebp_QL65_.jpg",
    brand: "Patanjali",
    price: "115",
    weight: "70ml",
    ratings: 4,
    categoryName: "Taila",
    fastDelivery: true,
    inStock: false,
  },
];
